---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

branches:
  only:
    - master

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn run lint:js
#  - yarn test
